version: "3.8"

services:
  artemis:
    container_name: artemis
    image: apache/activemq-artemis:latest-alpine
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - D:\Artemis\Docker\volume\:/docker_volume
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: adminpass