version: "3.8"

services:
  artemis:
    container_name: artemis
    image: apache/activemq-artemis:latest-alpine
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - D:\Artemis\Docker\volume\:/docker_volume
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ACTIVEMQ_SSL_OPTS: -Djavax.net.ssl.keyStore=/docker_volume/broker.ks -Djavax.net.ssl.keyStorePassword=keystorepass